name: develoment
description: "A new Flutter project."
publish_to: 'none' # 프로젝트를 pub.dev에 퍼블리시하지 않습니다.

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_naver_map: ^1.3.0
  stomp_dart_client: ^2.1.3
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true